openjdk/jcstress

.github/workflows/pre-integration.yml
JDK mainline had switched development to JDK 17 EA, we should be adding that version to pipelines.
---------
* [CODETOOLS-7902827](https://bugs.openjdk.java.net/browse/CODETOOLS-7902827): JCStress: Start testing with JDK 17 EA
`$ git fetch https://git.openjdk.java.net/jcstress pull/6/head:pull/6`
`$ git checkout pull/6`
=> CODETOOLS-7902827: JCStress: Start testing with JDK 17 EA

jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
JDK-8256535 added -XX:+StressCCP, jcstress should use it, as it already uses Stress{LCM,GCM,IGVN}.
---------
* [CODETOOLS-7902837](https://bugs.openjdk.java.net/browse/CODETOOLS-7902837): jcstress should support -XX:+StressCCP
`$ git fetch https://git.openjdk.java.net/jcstress pull/7/head:pull/7`
`$ git checkout pull/7`
=> CODETOOLS-7902837: jcstress should support -XX:+StressCCP

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
jcstress allows running multiple test per VM in order to optimize run times. Unfortunately, this feature gets in the way for reproducibility (multiple test contaminate the VM), error reporting (runner has to guess which test failed), and new features (like controlling the compilers). Thus, it is should go.
---------
* [CODETOOLS-7902848](https://bugs.openjdk.java.net/browse/CODETOOLS-7902848): jcstress: remove VM batching support
`$ git fetch https://git.openjdk.java.net/jcstress pull/10/head:pull/10`
`$ git checkout pull/10`
=> CODETOOLS-7902848: jcstress: remove VM batching support

jcstress-core/src/main/java/org/openjdk/jcstress/EmbeddedExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/TestResult.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java
Current jcstress code reports the TestResult for each iteration. While convenient to see the progress, it is ultimately noisy, and gets in the way of capturing the per-VM output. We can just accept a single test result per VM invocation, and rely on multiple forks to get verbose progress for long running tests.
---------
* [CODETOOLS-7902850](https://bugs.openjdk.java.net/browse/CODETOOLS-7902850): jcstress: Rework internal interfaces to get one TestResult per VM invocation
`$ git fetch https://git.openjdk.java.net/jcstress pull/12/head:pull/12`
`$ git checkout pull/12`
`$ git checkout pull/12`
`$ git pull https://git.openjdk.java.net/jcstress pull/12/head`
=> CODETOOLS-7902850: jcstress: Rework internal interfaces to get one TestResult per VM invocation

jcstress-core/src/main/java/org/openjdk/jcstress/EmbeddedExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/TestResult.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/HTMLReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java, jcstress-core/src/test/java/org/openjdk/jcstress/EmbeddedExecutorTest.java
In order to get PrintAssembly and other diagnostics from the forked VM, it would be instrumental for jcstress harness to capture the output from the forked VMs.
Example:
```
[OK] o.o.j.t.fences.UnfencedDekkerTest
(fork: #1, JVM args: [-Xlog:gc])
Observed state   Occurrences              Expectation  Interpretation                                              
0, 0       501,152   ACCEPTABLE_INTERESTING  Acceptable with no sequential consistency enforced          
0, 1   137,897,148               ACCEPTABLE  Acceptable under sequential consistency                     
1, 0   134,406,572               ACCEPTABLE  Acceptable under sequential consistency                     
1, 1           229               ACCEPTABLE  Acceptable under sequential consistency                     
VM output …
```
=> CODETOOLS-7902851: jcstress: Provide the ability to capture VM output

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/Verbosity.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/TextReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Following up on test failures is hard without the generated code. Doing -XX:+PrintAssembly would print the generated code for everything, which would be unnecessarily noisy. Luckily, we can now instruct jcstress to dump the generated code for the hot loops only.
Sample output:
```
$ java -jar tests-custom/target/jcstress.jar -t UnfencedDekker -vv --jvmArgs "-XX:-TieredCompilation"
Java Concurrency Stress Tests
---------------------------------------------------------------------------------
Rev: 728c24c414d9b9c2, built by shade with 11.0.12-testing at 2021-03-18T15:36:51Z
Burning up to figure out the exact CPU count....... done!
Probing the target OS:
(all failures are non-fatal, but may affect testing accuracy)
----- [OK] Trying to set affinity with taskset
Initializing and probing the …
```
=> CODETOOLS-7902854: jcstress: Print generated code assembly (optionally)

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Current GC options are questionable: the heap size too probably too large to be practical on large machines, and 4 GC threads oversubscribes the system after VM is taskset-s 2 CPUs for 2-actor tests.
---------
* [CODETOOLS-7902856](https://bugs.openjdk.java.net/browse/CODETOOLS-7902856): jcstress: Reconcile GC options
`$ git fetch https://git.openjdk.java.net/jcstress pull/15/head:pull/15`
`$ git checkout pull/15`
`$ git checkout pull/15`
`$ git pull https://git.openjdk.java.net/jcstress pull/15/head`
=> CODETOOLS-7902856: jcstress: Reconcile GC options

jcstress-benchmarks/src/main/java/org/openjdk/jcstress/SampleTestBench.java, jcstress-core/src/main/java/org/openjdk/jcstress/CompileMode.java, jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/StringUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/CompileMode.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java, jcstress-core/src/test/java/org/openjdk/jcstress/CompileModeTest.java, jcstress-core/src/test/java/org/openjdk/jcstress/EmbeddedExecutorTest.java
The groundwork that uses CompilerDirectives facility finally allows us to compile the actor methods with different compilers. This should catch inconsistencies in different compilers using incompatible memory barrier schemes.
---------
* [CODETOOLS-7902857](https://bugs.openjdk.java.net/browse/CODETOOLS-7902857): jcstress: Support split compilation modes
`$ git fetch https://git.openjdk.java.net/jcstress pull/16/head:pull/16`
`$ git checkout pull/16`
`$ git checkout pull/16`
`$ git pull https://git.openjdk.java.net/jcstress pull/16/head`
=> CODETOOLS-7902857: jcstress: Support split compilation modes

jcstress-benchmarks/src/main/java/org/openjdk/jcstress/SampleTestBench.java, jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java
Current progress message seems overloaded. Printing the number of tests and forks is misleading after multiple forks and multiple VMs are run per test. We can simplify the implementation considerably.
---------
* [CODETOOLS-7902858](https://bugs.openjdk.java.net/browse/CODETOOLS-7902858): jcstress: Clean up progress message
`$ git fetch https://git.openjdk.java.net/jcstress pull/17/head:pull/17`
`$ git checkout pull/17`
`$ git checkout pull/17`
`$ git pull https://git.openjdk.java.net/jcstress pull/17/head`
=> CODETOOLS-7902858: jcstress: Clean up progress message

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/TestResult.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/HTMLReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java
After VM output capture was enabled, the results file became exceedingly large. It is mostly due to recording the Whitebox messages. But, we can also cleanup the whole thing.
---------
* [CODETOOLS-7902861](https://bugs.openjdk.java.net/browse/CODETOOLS-7902861): jcstress: Optimize and clean up result handling
`$ git fetch https://git.openjdk.java.net/jcstress pull/18/head:pull/18`
`$ git checkout pull/18`
`$ git checkout pull/18`
`$ git pull https://git.openjdk.java.net/jcstress pull/18/head`
=> CODETOOLS-7902861: jcstress: Optimize and clean up result handling

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
Forked JVMs run in resource-constrained environments, where background compilation of hot task/run loops competes with the test execution itself. Also, when C1/C2 compilation is requested, we are better wait until that compilation actually happens.
---------
* [CODETOOLS-7902862](https://bugs.openjdk.java.net/browse/CODETOOLS-7902862): jcstress: Block execution of task/run loops until compiled code is available
`$ git fetch https://git.openjdk.java.net/jcstress pull/19/head:pull/19`
`$ git checkout pull/19`
`$ git checkout pull/19`
`$ git pull https://git.openjdk.java.net/jcstress pull/19/head`
=> CODETOOLS-7902862: jcstress: Block execution of task/run loops until compiled code is available

tests-custom/src/main/java/org/openjdk/jcstress/tests/volatiles/OpaqueIRIWTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/volatiles/RelaxedIRIWTest.java
This refactors the IRIW tests: makes sure the operands are in order, names unsyncronized test correct, introduces opaque test. Tested fine on x86_64 and PPC64.
---------
`$ git fetch https://git.openjdk.java.net/jcstress pull/20/head:pull/20`
`$ git checkout pull/20`
`$ git checkout pull/20`
`$ git pull https://git.openjdk.java.net/jcstress pull/20/head`
=> Refactor IRIW tests a bit

jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
CODETOOLS-7902854 added support for printing disassembly. Unfortunately, supplying PrintAssembly through compiler directives does not implicitly enables -XX:+DebugNonSafepoints, which makes disassembly less verbose: it misses PcDescs for non-safepoints.
---------
* [CODETOOLS-7902865](https://bugs.openjdk.java.net/browse/CODETOOLS-7902865): jcstress: Enable -XX:+DebugNonSafepoints if available to get more verbose disassembly
`$ git fetch https://git.openjdk.java.net/jcstress pull/21/head:pull/21` \
`$ git checkout pull/21`
`$ git checkout pull/21` \
`$ git pull https://git.openjdk.java.net/jcstress pull/21/head`
</details> …
=> CODETOOLS-7902865: jcstress: Enable -XX:+DebugNonSafepoints if available to get more verbose disassembly

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/CompileMode.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java, jcstress-core/src/test/java/org/openjdk/jcstress/CompileModeTest.java
Split compilation and other VM modes would futilely try to use C1 or C2 when not available. This affects Zero VM (has no C1/C2) and Minimal VM (has only C1). jcstress should autodetect the compiler availability and adjust itself accordingly.
---------
* [CODETOOLS-7902872](https://bugs.openjdk.java.net/browse/CODETOOLS-7902872): jcstress: check for C1/C2 availability and adjust configurations
`$ git fetch https://git.openjdk.java.net/jcstress pull/22/head:pull/22` \
`$ git checkout pull/22`
`$ git checkout pull/22` \
`$ git pull https://git.openjdk.java.net/jcstress pull/22/head`
</details>
`$ git pr …
=> CODETOOLS-7902872: jcstress: check for C1/C2 availability and adjust configurations

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/HTMLReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/TextReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/StringUtils.java
We can make the output a little bit better.
---------
* [CODETOOLS-7902873](https://bugs.openjdk.java.net/browse/CODETOOLS-7902873): jcstress: Clean up text reporting
`$ git fetch https://git.openjdk.java.net/jcstress pull/23/head:pull/23` \
`$ git checkout pull/23`
`$ git checkout pull/23` \
`$ git pull https://git.openjdk.java.net/jcstress pull/23/head`
</details>
`$ git pr checkout 23`
`$ git pr show -t 23`
</details>
<a href="https://git.openjdk.java.net/jcstress/pull/23.diff">https://git …
=> CODETOOLS-7902873: jcstress: Clean up text reporting

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java
Currently, jcstress does not print those when VM fails, which hinders the debugging.
---------
* [CODETOOLS-7902874](https://bugs.openjdk.java.net/browse/CODETOOLS-7902874): jcstress: Print messages and VM streams on VM failure
`$ git fetch https://git.openjdk.java.net/jcstress pull/24/head:pull/24` \
`$ git checkout pull/24`
`$ git checkout pull/24` \
`$ git pull https://git.openjdk.java.net/jcstress pull/24/head`
</details>
`$ git pr checkout 24`
`$ git pr show -t 24`
</details>
<a …
=> CODETOOLS-7902874: jcstress: Print messages and VM streams on VM failure

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java
CODETOOLS-7902872 rewrote CompileMode code, and introduced a little regression here:
https://github.com/openjdk/jcstress/commit/67158528f9abdf49f9ae23c704c068a76075b4fe?branch=67158528f9abdf49f9ae23c704c068a76075b4fe&diff=unified#diff-90c43d0da51e119c248c273763e3e5d3b6b14586492fb836c480ecd144af56e5L143-R144
The filter should say "config.onlyIfC2() && !hasC2". The "!" was accidentally dropped.
---------
* [CODETOOLS-7902877](https://bugs.openjdk.java.net/browse/CODETOOLS-7902877): jcstress: Fix C2-only configuration filtering
`$ git fetch https://git.openjdk.java.net/jcstress pull/25/head:pull/25` \
`$ git checkout pull/25`
`$ git checkout pull/25` \
`$ git pull …
=> CODETOOLS-7902877: jcstress: Fix C2-only configuration filtering

.github/workflows/pre-integration.yml
The testing pipeline for jcstress is quite heavy, and it would become even more heavy-weight with upcoming affinity improvements. Instead of running sanity tests (which disables forking), we can execute a handful of trial tests in full compilation/affinity matrix.
---------
`$ git fetch https://git.openjdk.java.net/jcstress pull/29/head:pull/29` \
`$ git checkout pull/29`
`$ git checkout pull/29` \
`$ git pull https://git.openjdk.java.net/jcstress pull/29/head`
</details>
`$ git pr checkout 29`
`$ git pr show -t 29`
</details>
<details><summary>Using diff …
=> CODETOOLS-7902883: jcstress: Do only a few trial tests in GitHub Actions

jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupport.java
After recent commits, Sonar reports a few warnings. These should be fixed.
---------
* [CODETOOLS-7902884](https://bugs.openjdk.java.net/browse/CODETOOLS-7902884): jcstress: Fix new Sonar warnings
`$ git fetch https://git.openjdk.java.net/jcstress pull/31/head:pull/31` \
`$ git checkout pull/31`
`$ git checkout pull/31` \
`$ git pull https://git.openjdk.java.net/jcstress pull/31/head`
</details>
`$ git pr checkout 31`
`$ git pr show -t 31`
</details>
<a …
=> CODETOOLS-7902884: jcstress: Fix new Sonar warnings

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java
It looks like "sanity" mode ignores the min/max stride settings, and so we enter sanityCheck_Footprints for it, producing more samples than we need. This makes "sanity" unnecessarily slow.
---------
* [CODETOOLS-7902903](https://bugs.openjdk.java.net/browse/CODETOOLS-7902903): jcstress: Optimize sanity preset mode
`$ git fetch https://git.openjdk.java.net/jcstress pull/34/head:pull/34` \
`$ git checkout pull/34`
`$ git checkout pull/34` \
`$ git pull https://git.openjdk.java.net/jcstress pull/34/head`
</details>
`$ git pr checkout 34`
`$ git pr show -t 34`
</details> …
=> CODETOOLS-7902903: jcstress: Optimize sanity preset mode

jcstress-core/src/main/java/org/openjdk/jcstress/ForkedMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/BinaryLinkClient.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/BinaryLinkServer.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/DoneFrame.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/ServerListener.java
Current TestExecutor code spins in the 100ms-wait loop for re-starting the next epoch of scheduling. This is way too large a wait for -m sanity. Reducing it to 10ms throws the non-sanity runs under the bus. We should instead do explicit waits for VM shutdown, and restart the scheduling then.
---------
* [CODETOOLS-7902904](https://bugs.openjdk.java.net/browse/CODETOOLS-7902904): jcstress: Explicit waits for VM shutdowns
`$ git fetch https://git.openjdk.java.net/jcstress pull/35/head:pull/35` \
`$ git checkout pull/35`
`$ git checkout pull/35` \
`$ git pull https://git.openjdk.java.net/jcstress pull/35/head`
</details>
Checkout …
=> CODETOOLS-7902904: jcstress: Explicit waits for VM shutdowns

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/SerializedBufferCollector.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/Scheduler.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/HashMultimap.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/Multimap.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/TreeMultimap.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/TreesetMultimap.java
Current scheduler walks the entire TestConfig list on every scheduling epoch. This was observed to be a bottleneck on large machines: the scheduler is unable to feed the entire machine with jobs. We can do much better by trying each scheduling class exactly once.
---------
* [CODETOOLS-7902905](https://bugs.openjdk.java.net/browse/CODETOOLS-7902905): jcstress: Improve scheduling performance
`$ git fetch https://git.openjdk.java.net/jcstress pull/36/head:pull/36` \
`$ git checkout pull/36`
`$ git checkout pull/36` \
`$ git pull https://git.openjdk.java.net/jcstress pull/36/head`
</details>
`$ git pr …
=> CODETOOLS-7902905: jcstress: Improve scheduling performance

jcstress-core/src/main/java/org/openjdk/jcstress/os/OSSupport.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
"FAILED" confuses users when received from the fairly innocuous code. "N/A" should work better.
---------
* [CODETOOLS-7902907](https://bugs.openjdk.java.net/browse/CODETOOLS-7902907): jcstress: Change "FAILED" to "N/A" in probing code
`$ git fetch https://git.openjdk.java.net/jcstress pull/38/head:pull/38` \
`$ git checkout pull/38`
`$ git checkout pull/38` \
`$ git pull https://git.openjdk.java.net/jcstress pull/38/head`
</details>
`$ git pr checkout 38`
`$ git pr show -t 38`
</details>
<a …
=> CODETOOLS-7902907: jcstress: Change "FAILED" to "N/A" in probing code

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/InputStreamCollector.java
jcstress puts stdin and stdout into separate temporary files. It makes little sense, as the host VM would read those files into memory anyway. We can just buffer those to memory.
Additionally, we can stop creating compiler directives file when it is not needed.
Options
---------
* [CODETOOLS-7902910](https://bugs.openjdk.java.net/browse/CODETOOLS-7902910): jcstress: Avoid creating lots of temporary files
`$ git fetch https://git.openjdk.java.net/jcstress pull/41/head:pull/41` \
`$ git checkout pull/41`
`$ git checkout pull/41` \
`$ git pull https://git.openjdk.java.net/jcstress pull/41/head`
</details> …
=> CODETOOLS-7902910: jcstress: Avoid creating lots of temporary files

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
Recent work introduced a few new complaints from Sonar. Let us fix them.
---------
* [CODETOOLS-7902911](https://bugs.openjdk.java.net/browse/CODETOOLS-7902911): jcstress: Fix new Sonar warnings
`$ git fetch https://git.openjdk.java.net/jcstress pull/42/head:pull/42` \
`$ git checkout pull/42`
`$ git checkout pull/42` \
`$ git pull https://git.openjdk.java.net/jcstress pull/42/head`
</details>
`$ git pr checkout 42`
`$ git pr show -t 42`
</details>
<a …
=> CODETOOLS-7902911: jcstress: Fix new Sonar warnings

jcstress-core/src/main/java/org/openjdk/jcstress/ForkedMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/TestResult.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/BinaryLinkClient.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/BinaryLinkServer.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/JobResponseFrame.java, jcstress-core/src/main/java/org/openjdk/jcstress/link/ServerListener.java
Current TestConfig is serialized and passed in full to the forked VMs. It carries a lot of baggage that forked VM does not really care about. We can instead pass a very limited subset of it. It also opens the way to use the small non-Java-Serialization format later.
---------
* [CODETOOLS-7902916](https://bugs.openjdk.java.net/browse/CODETOOLS-7902916): jcstress: Pass a limited subset of TestConfig to the forked VMs
`$ git fetch https://git.openjdk.java.net/jcstress pull/44/head:pull/44` \
`$ git checkout pull/44`
`$ git checkout pull/44` \
`$ git pull https://git.openjdk.java.net/jcstress pull/44/head`
</details>
Checkout this …
=> CODETOOLS-7902916: jcstress: Pass a limited subset of TestConfig to the forked VMs

jcstress-core/src/main/java/org/openjdk/jcstress/ForkedMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java
This is a regression since CODETOOLS-7902906. The interruption tests would never reply the result, because they call System.exit(0) before binary link is able to push the result.
---------
* [CODETOOLS-7902917](https://bugs.openjdk.java.net/browse/CODETOOLS-7902917): jcstress: Errors during interruption tests
`$ git fetch https://git.openjdk.java.net/jcstress pull/45/head:pull/45` \
`$ git checkout pull/45`
`$ git checkout pull/45` \
`$ git pull https://git.openjdk.java.net/jcstress pull/45/head`
</details>
`$ git pr checkout 45`
`$ git pr show -t 45`
</details> …
=> CODETOOLS-7902917: jcstress: Errors during interruption tests

jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/TestResult.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/Counter.java, jcstress-core/src/test/java/org/openjdk/jcstress/util/CounterTest.java
High-performance parts of jcstress code use open-address Counter to store state data. There is no reason why we cannot use Counter in the TestResults themselves.
---------
* [CODETOOLS-7902918](https://bugs.openjdk.java.net/browse/CODETOOLS-7902918): jcstress: Replace the relevant uses of HashMultiset with Counter
`$ git fetch https://git.openjdk.java.net/jcstress pull/46/head:pull/46` \
`$ git checkout pull/46`
`$ git checkout pull/46` \
`$ git pull https://git.openjdk.java.net/jcstress pull/46/head`
</details>
`$ git pr checkout 46`
`$ git pr show -t 46`
</details> …
=> CODETOOLS-7902918: jcstress: Replace the relevant uses of HashMultiset with Counter

jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/FootprintEstimator.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java
There are more tune ups in generated code in sight:
- reduce the use of lambdas
- reduce the use of collections
- avoid some unnecessary loops
- avoid excessive message handling
---------
* [CODETOOLS-7902922](https://bugs.openjdk.java.net/browse/CODETOOLS-7902922): jcstress: Tune up generated code once more
`$ git fetch https://git.openjdk.java.net/jcstress pull/50/head:pull/50` \
`$ git checkout pull/50`
`$ git checkout pull/50` \
`$ git pull https://git.openjdk.java.net/jcstress pull/50/head`
</details>
`$ git pr checkout 50`
`$ git pr show -t 50`
</details> …
=> CODETOOLS-7902922: jcstress: Tune up generated code once more

jcstress-core/src/main/java/org/openjdk/jcstress/ForkedMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/AbstractThread.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/CounterThread.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/LongThread.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/VoidThread.java
Forked VMs are executing the tests, and they are inherently using some concurrency primitives that might be under the test. Executors/Futures are the examples of such primitives. Since the jcstress uses are simple, we might as well do the hand-rolled implementations on bare Threads. This would improve test fidelity.
---------
* [CODETOOLS-7902923](https://bugs.openjdk.java.net/browse/CODETOOLS-7902923): jcstress: Eliminate dependency on Executors/Futures in forked VMs
`$ git fetch https://git.openjdk.java.net/jcstress pull/51/head:pull/51` \
`$ git checkout pull/51`
`$ git checkout pull/51` \
`$ git pull https://git.openjdk.java.net/jcstress pull/51/head`
</details> …
=> CODETOOLS-7902923: jcstress: Eliminate dependency on Executors/Futures in forked VMs

jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/AbstractThread.java
After recent work, Sonar complains about AbstractThread.
---------
* [CODETOOLS-7902925](https://bugs.openjdk.java.net/browse/CODETOOLS-7902925): jcstress: Fix new Sonar warnings
`$ git fetch https://git.openjdk.java.net/jcstress pull/52/head:pull/52` \
`$ git checkout pull/52`
`$ git checkout pull/52` \
`$ git pull https://git.openjdk.java.net/jcstress pull/52/head`
</details>
`$ git pr checkout 52`
`$ git pr show -t 52`
</details>
<a …
=> CODETOOLS-7902925: jcstress: Fix new Sonar warnings

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/annotations/Expect.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestList.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/Scheduler.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/StringUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/TestLineWriter.java
We can make the console UX even better: print JVM/CPU in use counts, print sample frequencies, etc.
---------
* [CODETOOLS-7902943](https://bugs.openjdk.java.net/browse/CODETOOLS-7902943): jcstress: Update console UX again
`$ git fetch https://git.openjdk.java.net/jcstress pull/53/head:pull/53` \
`$ git checkout pull/53`
`$ git checkout pull/53` \
`$ git pull https://git.openjdk.java.net/jcstress pull/53/head`
</details>
`$ git pr checkout 53`
`$ git pr show -t 53`
</details>
<a …
=> CODETOOLS-7902943: jcstress: Update console UX again

jcstress-core/src/main/java/org/openjdk/jcstress/ForkedMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupport.java
Currently, we eagerly initialize affinity support in ForkedMain, even when local affinity mode is not enabled. This eats precious time that we spend on doing unnecessary work.
---------
* [CODETOOLS-7902947](https://bugs.openjdk.java.net/browse/CODETOOLS-7902947): jcstress: Skip affinity initialization when non-local affinity mode is requested
`$ git fetch https://git.openjdk.java.net/jcstress pull/55/head:pull/55` \
`$ git checkout pull/55`
`$ git checkout pull/55` \
`$ git pull https://git.openjdk.java.net/jcstress pull/55/head`
</details>
`$ git pr checkout 55`
`$ …
=> CODETOOLS-7902947: jcstress: Skip affinity initialization when non-local affinity mode is requested

jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupport.java, pom.xml
jcstress still uses JNA 4.5.2. We can upgrade to 5.8.0 and thus take in bugfixes and extended platform support.
---------
* [CODETOOLS-7902946](https://bugs.openjdk.java.net/browse/CODETOOLS-7902946): jcstress: Upgrade JNA to 5.8.0
`$ git fetch https://git.openjdk.java.net/jcstress pull/54/head:pull/54` \
`$ git checkout pull/54`
`$ git checkout pull/54` \
`$ git pull https://git.openjdk.java.net/jcstress pull/54/head`
</details>
`$ git pr checkout 54`
`$ git pr show -t 54`
</details>
<a …
=> CODETOOLS-7902946: jcstress: Upgrade JNA to 5.8.0

jcstress-core/src/main/java/org/openjdk/jcstress/infra/Copyable.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/Counter.java, jcstress-result-gen/src/main/java/org/openjdk/jcstress/ResultGenerator.java
In jcstress, @Result instances can be reset in place. Which means that Counter has to do defensive copies before inserting results as keys. It now does it with serialization-deserialization stub. This takes about 10 ms to initialize on first key insertion. Fortunately, we can do better: if results are implicitly copyable (i.e. have only primitive fields), we can copy them directly.
---------
* [CODETOOLS-7902948](https://bugs.openjdk.java.net/browse/CODETOOLS-7902948): jcstress: Shortcut counter copy path for copyable results
`$ git fetch https://git.openjdk.java.net/jcstress pull/56/head:pull/56` \
`$ git checkout pull/56`
`$ git checkout pull/56` \
`$ git pull …
=> CODETOOLS-7902948: jcstress: Shortcut counter copy path for copyable results

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/InputStreamCollector.java
The TestExecutor loop is busy driving the run, and the blocking code that starts/finishes VMs should be offloaded to separate workers. Additionally, InputStreamCollectors that currently run as separate threads, can use the threadpool.
---------
* [CODETOOLS-7902950](https://bugs.openjdk.java.net/browse/CODETOOLS-7902950): jcstress: Offload VM start/finish/output tasks to separate workers
`$ git fetch https://git.openjdk.java.net/jcstress pull/58/head:pull/58` \
`$ git checkout pull/58`
`$ git checkout pull/58` \
`$ git pull https://git.openjdk.java.net/jcstress pull/58/head`
</details>
`$ git pr …
=> CODETOOLS-7902950: jcstress: Offload VM start/finish/output tasks to separate workers

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupport.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/OSSupport.java, jcstress-core/src/test/java/org/openjdk/jcstress/os/AffinitySupportTest.java
Forked VMs unpack JNA libraries on every invocation. Those should actually be unpacked once by host VM, and then reused by forked VMs.
This saves about 30 ms per forked VM invocation.
---------
* [CODETOOLS-7902951](https://bugs.openjdk.java.net/browse/CODETOOLS-7902951): jcstress: Optimize JNA loading paths
`$ git fetch https://git.openjdk.java.net/jcstress pull/59/head:pull/59` \
`$ git checkout pull/59`
`$ git checkout pull/59` \
`$ git pull https://git.openjdk.java.net/jcstress pull/59/head`
</details>
`$ git pr checkout 59`
`$ git pr show -t 59`
</details> …
=> CODETOOLS-7902951: jcstress: Optimize JNA loading paths

jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Sample runs shows >10 MB/s write I/O with -m sanity on large machine. Those writes seem to originate from UsePerfData subsystem. We should do -XX:-UsePerfData, since jcstress does not need it anyway.
---------
* [CODETOOLS-7902952](https://bugs.openjdk.java.net/browse/CODETOOLS-7902952): jcstress: Disable UsePerfData to improve I/O costs
`$ git fetch https://git.openjdk.java.net/jcstress pull/60/head:pull/60` \
`$ git checkout pull/60`
`$ git checkout pull/60` \
`$ git pull https://git.openjdk.java.net/jcstress pull/60/head`
</details>
`$ git pr checkout 60`
`$ git pr …
=> CODETOOLS-7902952: jcstress: Disable UsePerfData to improve I/O costs

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/StringUtils.java
See the changeset.
---------
* [CODETOOLS-7902953](https://bugs.openjdk.java.net/browse/CODETOOLS-7902953): jcstress: Minor touchups for status line and percent reporting
`$ git fetch https://git.openjdk.java.net/jcstress pull/61/head:pull/61` \
`$ git checkout pull/61`
`$ git checkout pull/61` \
`$ git pull https://git.openjdk.java.net/jcstress pull/61/head`
</details>
`$ git pr checkout 61`
`$ git pr show -t 61`
</details>
<a href="https://git.openjdk.java.net/jcstress/pull/61.diff">https:/ …
=> CODETOOLS-7902953: jcstress: Minor touchups for status line and percent reporting

jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupport.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupportTestMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/OSSupport.java
This is a regression from CODETOOLS-7902951. We need to move the unpacked library to the proper name, so that forked VM loader would discover it properly.
---------
* [CODETOOLS-7902954](https://bugs.openjdk.java.net/browse/CODETOOLS-7902954): jcstress: Move unpacked JNA library to proper name
`$ git fetch https://git.openjdk.java.net/jcstress pull/62/head:pull/62` \
`$ git checkout pull/62`
`$ git checkout pull/62` \
`$ git pull https://git.openjdk.java.net/jcstress pull/62/head`
</details>
`$ git pr checkout 62`
`$ git pr show -t 62`
</details> …
=> CODETOOLS-7902954: jcstress: Move unpacked JNA library to proper name

jcstress-core/src/test/java/org/openjdk/jcstress/infra/results/I_Result_Test.java, jcstress-core/src/test/java/org/openjdk/jcstress/infra/results/L_Result_Test.java, jcstress-result-gen/src/main/java/org/openjdk/jcstress/ResultGenerator.java
Due to a bug in ResultGenerator, all L-results are ignoring the reference in hashCode/equals computation. This means all results that have only reference results are equal to each other, and only the first result would be counted.
---------
* [CODETOOLS-7902957](https://bugs.openjdk.java.net/browse/CODETOOLS-7902957): jcstress: L-results are always equal to each other
`$ git fetch https://git.openjdk.java.net/jcstress pull/63/head:pull/63` \
`$ git checkout pull/63`
`$ git checkout pull/63` \
`$ git pull https://git.openjdk.java.net/jcstress pull/63/head`
</details>
`$ git pr checkout 63`
View PR using …
=> CODETOOLS-7902957: jcstress: L-results are always equal to each other

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/HTMLReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/TextReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/CompileMode.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
When jcstress is presented with large font, the status line is too long to be useful. We can use multi-line ANSI codes to break it into pieces.
---------
* [CODETOOLS-7902959](https://bugs.openjdk.java.net/browse/CODETOOLS-7902959): jcstress: Update progress line to ANSI multi-line for better presentation
`$ git fetch https://git.openjdk.java.net/jcstress pull/65/head:pull/65` \
`$ git checkout pull/65`
`$ git checkout pull/65` \
`$ git pull https://git.openjdk.java.net/jcstress pull/65/head`
</details>
`$ git pr checkout 65`
`$ git pr show -t 65`
</details> …
=> CODETOOLS-7902959: jcstress: Update progress line to ANSI multi-line for better presentation

tests-all/pom.xml
It makes little sense to avoid jcstress samples from tests-all bundle. Adding samples to tests-all bundle also implicitly verifies them during the normal concurrency testing.
---------
* [CODETOOLS-7902961](https://bugs.openjdk.java.net/browse/CODETOOLS-7902961): jcstress: Add jcstress-samples to tests-all bundle
`$ git fetch https://git.openjdk.java.net/jcstress pull/66/head:pull/66` \
`$ git checkout pull/66`
`$ git checkout pull/66` \
`$ git pull https://git.openjdk.java.net/jcstress pull/66/head`
</details>
`$ git pr checkout 66`
`$ git pr show -t 66`
</details> …
=> CODETOOLS-7902961: jcstress: Add jcstress-samples to tests-all bundle

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/TextReportPrinter.java
It makes little sense to print the per-configuration results at the end of the run, when the run itself prints it. We are better off printing the merged results across all configurations.
---------
* [CODETOOLS-7902962](https://bugs.openjdk.java.net/browse/CODETOOLS-7902962): jcstress: Print merged results at the end of the run
`$ git fetch https://git.openjdk.java.net/jcstress pull/67/head:pull/67` \
`$ git checkout pull/67`
`$ git checkout pull/67` \
`$ git pull https://git.openjdk.java.net/jcstress pull/67/head`
</details>
`$ git pr checkout 67`
`$ git pr show -t …
=> CODETOOLS-7902962: jcstress: Print merged results at the end of the run

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/SpinLoopStyle.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/WorkerSync.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/fences/UnfencedDekkerTest.java
Currently, the harness uses larger strides to run and consume the results of the test. Unfortunately, when actor threads are unbalanced (e.g. run asymmetric workloads), there is a single collision per entire stride. Having shorter strides would increase collision ratios, but would create much more overhead for creating/consuming benchmark results and state.
We can do long "epoch" with several shorter "strides" and spin-loop checkpointing between strides, so that threads can catch up more often.
---------
* [CODETOOLS-7902964](https://bugs.openjdk.java.net/browse/CODETOOLS-7902964): jcstress: Introduce short-stride checkpointing for more frequent collisions
`$ git fetch https://git.openjdk.java.net/jcstress …
=> CODETOOLS-7902964: jcstress: Introduce short-stride checkpointing for more frequent collisions

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java
Most of the time, small number of samples yields "<0.1%". It would be better to produce the more precise frequency stats, one order of magnitude more.
---------
* [CODETOOLS-7902965](https://bugs.openjdk.java.net/browse/CODETOOLS-7902965): jcstress: Enhance FREQ precision to 0.01%
`$ git fetch https://git.openjdk.java.net/jcstress pull/70/head:pull/70` \
`$ git checkout pull/70`
`$ git checkout pull/70` \
`$ git pull https://git.openjdk.java.net/jcstress pull/70/head`
</details>
`$ git pr checkout 70`
`$ git pr show -t 70`
</details>
<details><summary>Using diff …
=> CODETOOLS-7902965: jcstress: Enhance FREQ precision to 0.01%

jcstress-core/src/main/java/org/openjdk/jcstress/util/UnsafeHolder.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/ContendedTestMain.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/JMMSample_01_AccessAtomicity.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/atomicity/crosscache/UnsafeIntAtomicityTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/fences/FencedAcquireReleaseTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/fences/FencedDekkerTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/fences/FencedPublicationTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/fences/FencedReadTwiceTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/BooleanFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/ByteFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/CharFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/DoubleFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/FloatFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/IntFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/LongFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/init/primitives/fenced/ShortFencedTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/interrupt/UnsafeBusyLoopTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/tearing/UnsafeArrayInterleaveTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/tearing/UnsafeIntTearingTest.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/unsafe/UnsafeAddLong1.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/unsafe/UnsafeAddLong42.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/unsafe/UnsafePutOrderedTwice.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/unsafe/UnsafeReadTwiceOverVolatileReadTest.java
Currently we use `UnsafeHolder` in test infra and tests, and we can make those usages more straightforward.
---------
* [CODETOOLS-7902967](https://bugs.openjdk.java.net/browse/CODETOOLS-7902967): jcstress: Rehash Unsafe usages in infrastructure and tests
`$ git fetch https://git.openjdk.java.net/jcstress pull/71/head:pull/71` \
`$ git checkout pull/71`
`$ git checkout pull/71` \
`$ git pull https://git.openjdk.java.net/jcstress pull/71/head`
</details>
`$ git pr checkout 71`
`$ git pr show -t 71`
</details>
Download this PR …
=> CODETOOLS-7902967: jcstress: Rehash Unsafe usages in infrastructure and tests

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_08_WrongListReleaseOrder.java
There is apparently a missing outcome when the backing array is already resized, but the store did not happen yet.
---------
* [CODETOOLS-7902969](https://bugs.openjdk.java.net/browse/CODETOOLS-7902969): jcstress: Fix AdvancedJMM_08_WrongListReleaseOrder test
`$ git fetch https://git.openjdk.java.net/jcstress pull/73/head:pull/73` \
`$ git checkout pull/73`
`$ git checkout pull/73` \
`$ git pull https://git.openjdk.java.net/jcstress pull/73/head`
</details>
`$ git pr checkout 73`
`$ git pr show -t 73`
</details>
Download this …
=> CODETOOLS-7902969: jcstress: Fix AdvancedJMM_08_WrongListReleaseOrder test

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
Look here:
```
// If this actor runs in interpreted mode, then actor method should not be compiled.
// Allow run loop to be compiled with the best compiler available.
if (CompileMode.isInt(cm, a)) {
pw.println(" {");
pw.println(" match: \"+" + task.name + "::" + an + "\",");
```
The "+" sign there is a copy-paste error from a relevant "inline" block. But "+" makes no sense in "match", and it would always mismatch. That means the "interpreter" split configuration are actually compiling.
---------
* [CODETOOLS-7902971](https://bugs.openjdk.java.net/browse/CODETOOLS-7902971): jcstress: Interepreted mode match is incorrect
`$ git fetch https://git.openjdk.java.net/jcstress pull/74/head:pull/74` \
`$ git checkout …
=> CODETOOLS-7902971: jcstress: Interepreted mode match is incorrect

jcstress-benchmarks/src/main/java/org/openjdk/jcstress/SampleTestBench.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/TestInfo.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestList.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
This seems to cause issues for nested classes. Annotation processor normally answers the "qualified name", which concatenates the nested class name with ".". Compiler directives expect nested class names to be concatenated with "$", that is, expect the binary class name.
Currently, requested-to-run-in-interpreter nested class methods would mismatch and be compiled.
---------
* [CODETOOLS-7902973](https://bugs.openjdk.java.net/browse/CODETOOLS-7902973): jcstress: Compiler directives should include binary, not qualified class names
`$ git fetch https://git.openjdk.java.net/jcstress pull/75/head:pull/75` \
`$ git checkout pull/75`
`$ git checkout pull/75` \
`$ git pull …
=> CODETOOLS-7902973: jcstress: Compiler directives should include binary, not qualified class names

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
Currently, actor methods can be called from the sanity checks, thus bypassing the non-inlineablitity directives for run loops. A similar issue is with worker thread and task loop: task loop configuration should take precedence over (default) worker thread config.
---------
* [CODETOOLS-7902972](https://bugs.openjdk.java.net/browse/CODETOOLS-7902972): jcstress: Worker thread methods should not inline further calls
`$ git fetch https://git.openjdk.java.net/jcstress pull/76/head:pull/76` \
`$ git checkout pull/76`
`$ git checkout pull/76` \
`$ git pull https://git.openjdk.java.net/jcstress pull/76/head`
</details>
Checkout this PR …
=> CODETOOLS-7902972: jcstress: Worker thread methods should not inline further calls

jcstress-core/src/main/java/org/openjdk/jcstress/util/UnsafeHolder.java, jcstress-core/src/main/java/sun/misc/Unsafe.java
Look at the bug for the build failure log.
---------
* [CODETOOLS-7902975](https://bugs.openjdk.java.net/browse/CODETOOLS-7902975): jcstress: JDK 17 cannot cleanly compile due to SecurityManager deprecation
`$ git fetch https://git.openjdk.java.net/jcstress pull/78/head:pull/78` \
`$ git checkout pull/78`
`$ git checkout pull/78` \
`$ git pull https://git.openjdk.java.net/jcstress pull/78/head`
</details>
`$ git pr checkout 78`
`$ git pr show -t 78`
</details>
<a …
=> CODETOOLS-7902975: jcstress: JDK 17 cannot cleanly compile due to SecurityManager deprecation

jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java
Current "arrays.large" are failing with OOM because estimator only balances the stride count, while leaving stride size at 256. This is a recent regression.
---------
* [CODETOOLS-7902974](https://bugs.openjdk.java.net/browse/CODETOOLS-7902974): jcstress: Footprint estimator should balance both stride count and stride size
`$ git fetch https://git.openjdk.java.net/jcstress pull/77/head:pull/77` \
`$ git checkout pull/77`
`$ git checkout pull/77` \
`$ git pull https://git.openjdk.java.net/jcstress pull/77/head`
</details>
`$ git pr checkout 77`
`$ git pr show -t 77` …
=> CODETOOLS-7902974: jcstress: Footprint estimator should balance both stride count and stride size

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_01_SynchronizedBarriers.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_02_MultiCopyAtomic.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_04_MisplacedVolatile.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_08_WrongListReleaseOrder.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_12_VolatilesAreNotFences.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_01_DataRaces.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_02_AccessAtomicity.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_04_Progress.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_05_Coherence.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_06_Causality.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_09_BenignRaces.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_10_OOTA.java
Some post-review comments emerged for jcstress-samples, this should make them cleaner.
---------
* [CODETOOLS-7902977](https://bugs.openjdk.java.net/browse/CODETOOLS-7902977): jcstress: Minor touchups for jcstress-samples
`$ git fetch https://git.openjdk.java.net/jcstress pull/80/head:pull/80` \
`$ git checkout pull/80`
`$ git checkout pull/80` \
`$ git pull https://git.openjdk.java.net/jcstress pull/80/head`
</details>
`$ git pr checkout 80`
`$ git pr show -t 80`
</details>
<a …
=> CODETOOLS-7902977: jcstress: Minor touchups for jcstress-samples

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/api/API_01_Simple.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/api/API_02_Arbiters.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/api/API_03_Termination.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/api/API_04_Nesting.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/api/API_05_SharedMetadata.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/api/API_06_Descriptions.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_01_SynchronizedBarriers.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_02_MultiCopyAtomic.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_03_LosingUpdates.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_08_WrongListReleaseOrder.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_11_VolatileVsFinal.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_12_SynchronizedAreNotFences.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_13_VolatilesAreNotFences.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_03_WordTearing.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_06_Causality.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_07_Consensus.java
These updates follow the recent JCStress Workshop and fix issues discovered there.
---------
* [CODETOOLS-7902979](https://bugs.openjdk.java.net/browse/CODETOOLS-7902979): jcstress: Another round of samples updates
`$ git fetch https://git.openjdk.java.net/jcstress pull/81/head:pull/81` \
`$ git checkout pull/81`
`$ git checkout pull/81` \
`$ git pull https://git.openjdk.java.net/jcstress pull/81/head`
</details>
`$ git pr checkout 81`
`$ git pr show -t 81`
</details>
<a …
=> CODETOOLS-7902979: jcstress: Another round of samples updates

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
There a couple of places where trailing whitespaces take a lot of space and induce wrapping where it is not expected.
---------
* [CODETOOLS-7902981](https://bugs.openjdk.java.net/browse/CODETOOLS-7902981): jcstress: Remove trailing whitespaces in the console log
`$ git fetch https://git.openjdk.java.net/jcstress pull/83/head:pull/83` \
`$ git checkout pull/83`
`$ git checkout pull/83` \
`$ git pull https://git.openjdk.java.net/jcstress pull/83/head`
</details>
`$ git pr checkout 83`
`$ git pr show -t 83`
</details>
Download …
=> CODETOOLS-7902981: jcstress: Remove trailing whitespaces in the console log

jcstress-core/src/main/java/org/openjdk/jcstress/infra/collectors/TestResult.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/HTMLReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/TestGrading.java
As reported here:
https://mail.openjdk.java.net/pipermail/jcstress-dev/2021-June/000702.html
Cache the grading, optimize HTML table generation a little.
---------
* [CODETOOLS-7902983](https://bugs.openjdk.java.net/browse/CODETOOLS-7902983): jcstress: Improve performance for tests with many results
`$ git fetch https://git.openjdk.java.net/jcstress pull/86/head:pull/86` \
`$ git checkout pull/86`
`$ git checkout pull/86` \
`$ git pull https://git.openjdk.java.net/jcstress pull/86/head`
</details>
`$ git pr checkout 86`
`$ git pr show -t 86`
</details> …
=> CODETOOLS-7902983: jcstress: Improve performance for tests with many results

jcstress-core/pom.xml, jcstress-core/src/main/java/org/openjdk/jcstress/Main.java, jcstress-core/src/main/java/org/openjdk/jcstress/annotations/JCStressMeta.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/Scheduler.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/ResultUtils.java, jcstress-core/src/main/java/sun/misc/Unsafe.java, jcstress-result-gen/src/main/java/org/openjdk/jcstress/ResultGenerator.java, jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/TestGenerator.java, jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/seqcst/SeqCstTraceGenerator.java, jcstress-test-gen/src/main/resources/fences/X-LoadStoreFenceTest1.java.template, jcstress-test-gen/src/main/resources/fences/X-LoadStoreFenceTest2.java.template, pom.xml
See bug report for details.
---------
* [CODETOOLS-7902984](https://bugs.openjdk.java.net/browse/CODETOOLS-7902984): jcstress: Fix lint warnings in generated code and utilities
`$ git fetch https://git.openjdk.java.net/jcstress pull/87/head:pull/87` \
`$ git checkout pull/87`
`$ git checkout pull/87` \
`$ git pull https://git.openjdk.java.net/jcstress pull/87/head`
</details>
`$ git pr checkout 87`
`$ git pr show -t 87`
</details>
<a …
=> CODETOOLS-7902984: jcstress: Fix lint warnings in generated code and utilities

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_12_SynchronizedAreNotFences.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_13_VolatilesAreNotFences.java
It would be a good example to actually use load/storeFences in the examples instead of fullFence. This demonstrates the effect better.
---------
* [CODETOOLS-7902992](https://bugs.openjdk.java.net/browse/CODETOOLS-7902992): jcstress: Amend *NotFences tests to use weakest fences
`$ git fetch https://git.openjdk.java.net/jcstress pull/89/head:pull/89` \
`$ git checkout pull/89`
`$ git checkout pull/89` \
`$ git pull https://git.openjdk.java.net/jcstress pull/89/head`
</details>
`$ git pr checkout 89`
`$ git pr show -t 89`
</details>
<details><summary>Using diff …
=> CODETOOLS-7902992: jcstress: Amend *NotFences tests to use weakest fences

tests-custom/src/main/java/org/openjdk/jcstress/tests/mxbeans/ThreadMXBeanAlloc.java
This adds the test to demonstrate the racy behavior of TLAB allocation data:
```
$ mvn clean install -pl tests-custom
$ java -jar tests-custom/target/jcstress.jar -t ThreadMXBeanAlloc
.......... [OK] o.o.j.t.mxbeans.ThreadMXBeanAlloc
Results across all configurations:
RESULT SAMPLES FREQ EXPECT DESCRIPTION
false, true 2,901 <0.01% Interesting At least one thread experiences delta <0
true, false 4,232 <0.01% Interesting At least one thread experiences delta <0
true, true 258,364,451 100.00% Acceptable Delta is >= 0
```
---------
* [CODETOOLS-7902998](https://bugs.openjdk.java.net/browse/CODETOOLS-7902998): jcstress: Add new ThreadMXBeanAlloc test
`$ git fetch https://git.openjdk.java.net/jcstress …
=> CODETOOLS-7902998: jcstress: Add new ThreadMXBeanAlloc test

jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/Atomic_Updater_X.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/atomics/integer/AtomicIntegerFieldUpdaterPairwiseTests.java, tests-custom/src/main/java/org/openjdk/jcstress/tests/atomics/longs/AtomicLongFieldUpdaterPairwiseTests.java
A*FU performance depends on the ability to fold the internal checks, which is possible when instances are in "static final". We need to make sure tests do that.
---------
* [CODETOOLS-7902999](https://bugs.openjdk.java.net/browse/CODETOOLS-7902999): jcstress: Make sure A*FU tests are holding instances in static finals
`$ git fetch https://git.openjdk.java.net/jcstress pull/91/head:pull/91` \
`$ git checkout pull/91`
`$ git checkout pull/91` \
`$ git pull https://git.openjdk.java.net/jcstress pull/91/head`
</details>
`$ git pr checkout 91`
`$ git pr show -t 91` …
=> CODETOOLS-7902999: jcstress: Make sure A*FU tests are holding instances in static finals

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/HTMLReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java
HTML report is quite misleading after recent compilation/scheduling modes introduction. It needs some rework.
---------
* [CODETOOLS-7903039](https://bugs.openjdk.java.net/browse/CODETOOLS-7903039): jcstress: HTML reports should capture compilation/scheduling modes
`$ git fetch https://git.openjdk.java.net/jcstress pull/98/head:pull/98` \
`$ git checkout pull/98`
`$ git checkout pull/98` \
`$ git pull https://git.openjdk.java.net/jcstress pull/98/head`
</details>
`$ git pr checkout 98`
`$ git pr show -t 98`
</details> …
=> CODETOOLS-7903039: jcstress: HTML reports should capture compilation/scheduling modes

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Stress C2 modes are random, it makes sense to run them in more forks to have more opportunities for (un)lucky compilation.
---------
* [CODETOOLS-7903040](https://bugs.openjdk.java.net/browse/CODETOOLS-7903040): jcstress: Introduce stress configuration multipliers
`$ git fetch https://git.openjdk.java.net/jcstress pull/99/head:pull/99` \
`$ git checkout pull/99`
`$ git checkout pull/99` \
`$ git pull https://git.openjdk.java.net/jcstress pull/99/head`
</details>
`$ git pr checkout 99`
`$ git pr show -t 99`
</details>
Download …
=> CODETOOLS-7903040: jcstress: Introduce stress configuration multipliers

.github/workflows/pre-integration.yml
With the release of JDK 17, we need to reconsider tested versions in GHA.
---------
* [CODETOOLS-7903049](https://bugs.openjdk.java.net/browse/CODETOOLS-7903049): jcstress: Reconsider tested JDK versions
`$ git fetch https://git.openjdk.java.net/jcstress pull/101/head:pull/101` \
`$ git checkout pull/101`
`$ git checkout pull/101` \
`$ git pull https://git.openjdk.java.net/jcstress pull/101/head`
</details>
`$ git pr checkout 101`
`$ git pr show -t 101`
</details>
<a …
=> CODETOOLS-7903049: jcstress: Reconsider tested JDK versions

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/high/rmw/RMW_10_FailureWitness.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/high/rmw/RMW_11_FailureWitnessRWL.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/high/rmw/RMW_12_FailureWitnessLoops.java
We need to improve the jcstress samples with some failure witness examples. 
---------
* [CODETOOLS-7903052](https://bugs.openjdk.java.net/browse/CODETOOLS-7903052): jcstress: Failure witness examples
`$ git fetch https://git.openjdk.java.net/jcstress pull/96/head:pull/96` \
`$ git checkout pull/96`
`$ git checkout pull/96` \
`$ git pull https://git.openjdk.java.net/jcstress pull/96/head`
</details>
`$ git pr checkout 96`
`$ git pr show -t 96`
</details>
<a …
=> CODETOOLS-7903052: jcstress: Failure witness examples

jcstress-benchmarks/src/main/java/org/openjdk/jcstress/SampleTestBench.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/CPUMap.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/Scheduler.java, jcstress-core/src/test/java/org/openjdk/jcstress/os/AbstractSchedulerAffinityTest.java
Currently, running with -af NONE, still prints CPU allocation lists. Those are actually fake, and bear no meaning. They should not be printed at all.
---------
* [CODETOOLS-7903065](https://bugs.openjdk.java.net/browse/CODETOOLS-7903065): jcstress: Do not print CPU allocations for NONE affinity mode
`$ git fetch https://git.openjdk.java.net/jcstress pull/107/head:pull/107` \
`$ git checkout pull/107`
`$ git checkout pull/107` \
`$ git pull https://git.openjdk.java.net/jcstress pull/107/head`
</details>
`$ git pr checkout 107`
`$ git pr show -t 107`
</details> …
=> CODETOOLS-7903065: jcstress: Do not print CPU allocations for NONE affinity mode

jcstress-core/src/main/java/org/openjdk/jcstress/os/topology/FallbackTopology.java
Those layouts are fake, they are not used anywhere, and can be skipped from printing.
---------
* [CODETOOLS-7903066](https://bugs.openjdk.java.net/browse/CODETOOLS-7903066): jcstress: Do not print fake CPU mappings from FallbackTopology
`$ git fetch https://git.openjdk.java.net/jcstress pull/108/head:pull/108` \
`$ git checkout pull/108`
`$ git checkout pull/108` \
`$ git pull https://git.openjdk.java.net/jcstress pull/108/head`
</details>
`$ git pr checkout 108`
`$ git pr show -t 108`
</details>
Download this PR as a diff …
=> CODETOOLS-7903066: jcstress: Do not print fake CPU mappings from FallbackTopology

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/problems/classic/Classic_01_DiningPhilosophers.java
SoundCloud found this little oddity. Let's fix it.
---------
* [CODETOOLS-7903070](https://bugs.openjdk.java.net/browse/CODETOOLS-7903070): jcstress: Typo in Classic_01_DiningPhilosophers sample
`$ git fetch https://git.openjdk.java.net/jcstress pull/109/head:pull/109` \
`$ git checkout pull/109`
`$ git checkout pull/109` \
`$ git pull https://git.openjdk.java.net/jcstress pull/109/head`
</details>
`$ git pr checkout 109`
`$ git pr show -t 109`
</details>
<a …
=> CODETOOLS-7903070: jcstress: Typo in Classic_01_DiningPhilosophers sample

.github/workflows/pre-integration.yml
Similar to [JDK-8282225](https://bugs.openjdk.java.net/browse/JDK-8282225), we want the same for jcstress.
---------
* [CODETOOLS-7903112](https://bugs.openjdk.java.net/browse/CODETOOLS-7903112): jcstress: GHA: Allow one concurrent run per PR only
`$ git fetch https://git.openjdk.java.net/jcstress pull/113/head:pull/113` \
`$ git checkout pull/113`
`$ git checkout pull/113` \
`$ git pull https://git.openjdk.java.net/jcstress pull/113/head`
</details>
`$ git pr checkout 113`
`$ git pr show -t 113`
</details>
Download this PR …
=> CODETOOLS-7903112: jcstress: GHA: Allow one concurrent run per PR only 

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_07_SemiVolatile.java
A slight documentation regression since [CODETOOLS-7903107](https://bugs.openjdk.java.net/browse/CODETOOLS-7903107).
---------
* [CODETOOLS-7903114](https://bugs.openjdk.java.net/browse/CODETOOLS-7903114): jcstress: Amend AdvancedJMM_07_SemiVolatile test result
`$ git fetch https://git.openjdk.java.net/jcstress pull/112/head:pull/112` \
`$ git checkout pull/112`
`$ git checkout pull/112` \
`$ git pull https://git.openjdk.java.net/jcstress pull/112/head`
</details>
`$ git pr checkout 112`
`$ git pr show -t 112`
</details> …
=> CODETOOLS-7903114: jcstress: Amend AdvancedJMM_07_SemiVolatile test result 

.github/workflows/pre-integration.yml
GHA workflows need to have a push-based trigger instead of pull_request one, in order to comply with current scheme of running actions in private forks.
---------
* [CODETOOLS-7903233](https://bugs.openjdk.org/browse/CODETOOLS-7903233): jcstress: Improve GHA triggers
`$ git fetch https://git.openjdk.org/jcstress pull/116/head:pull/116` \
`$ git checkout pull/116`
`$ git checkout pull/116` \
`$ git pull https://git.openjdk.org/jcstress pull/116/head`
</details>
`$ git pr checkout 116`
`$ git pr show -t 116`
</details>
Download …
=> CODETOOLS-7903233: jcstress: Improve GHA triggers

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_04_Progress.java, jcstress-samples/src/main/java/org/openjdk/jcstress/samples/problems/classic/Classic_01_DiningPhilosophers.java
Improves the progress guarantees handling in samples.
---------
* [CODETOOLS-7903236](https://bugs.openjdk.org/browse/CODETOOLS-7903236): jcstress: Improve Classic_01_DiningPhilosophers test
`$ git fetch https://git.openjdk.org/jcstress pull/117/head:pull/117` \
`$ git checkout pull/117`
`$ git checkout pull/117` \
`$ git pull https://git.openjdk.org/jcstress pull/117/head`
</details>
`$ git pr checkout 117`
`$ git pr show -t 117`
</details>
<a …
=> CODETOOLS-7903236: jcstress: Improve Classic_01_DiningPhilosophers test

jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/Counter.java, jcstress-core/src/test/java/org/openjdk/jcstress/util/CounterTest.java
Currently, jcstress uses a "convenience" method on a hot path, which delegates to the real one. This relies on JIT compilers to inline it through. We don't have to rely on this, and can call the full method directly.
---------
* [CODETOOLS-7903290](https://bugs.openjdk.org/browse/CODETOOLS-7903290): jcstress: Inline Counter.record(R) method
`$ git fetch https://git.openjdk.org/jcstress pull/120/head:pull/120` \
`$ git checkout pull/120`
`$ git checkout pull/120` \
`$ git pull https://git.openjdk.org/jcstress pull/120/head`
</details>
`$ git pr checkout 120`
`$ git pr …
=> CODETOOLS-7903290: jcstress: Inline Counter.record(R) method

jcstress-core/src/main/java/org/openjdk/jcstress/vm/AllocProfileSupport.java
[CODETOOLS-7903216](https://bugs.openjdk.org/browse/CODETOOLS-7903216) introduced a regression where allocation profiling was ruled to be unavailable on older JDKs.
---------
* [CODETOOLS-7903292](https://bugs.openjdk.org/browse/CODETOOLS-7903292): jcstress: Allocation profiling is not available on older JDKs
`$ git fetch https://git.openjdk.org/jcstress pull/122/head:pull/122` \
`$ git checkout pull/122`
`$ git checkout pull/122` \
`$ git pull https://git.openjdk.org/jcstress pull/122/head`
</details>
`$ git pr checkout 122`
`$ git pr show -t 122`
</details> …
=> CODETOOLS-7903292: jcstress: Allocation profiling is not available on older JDKs

.github/workflows/pre-integration.yml
Time to update our workflows: new JDKs, new OSes, new GH plugins.
---------
* [CODETOOLS-7903365](https://bugs.openjdk.org/browse/CODETOOLS-7903365): jcstress: Update pre-integration testing workflows
`$ git fetch https://git.openjdk.org/jcstress pull/123/head:pull/123` \
`$ git checkout pull/123`
`$ git checkout pull/123` \
`$ git pull https://git.openjdk.org/jcstress pull/123/head`
</details>
`$ git pr checkout 123`
`$ git pr show -t 123`
</details>
<a …
=> CODETOOLS-7903365: jcstress: Update pre-integration testing workflows

jcstress-core/src/main/java/org/openjdk/jcstress/Main.java
```
Warning: COMPILATION WARNING :
[INFO] -------------------------------------------------------------
Warning: /home/runner/work/jcstress/jcstress/jcstress-core/src/main/java/org/openjdk/jcstress/Main.java:[74,22] URL(java.lang.String) in java.net.URL has been deprecated
```
---------
* [CODETOOLS-7903407](https://bugs.openjdk.org/browse/CODETOOLS-7903407): jcstress: Main cannot compile with -Werror due to URL deprecation
`$ git fetch https://git.openjdk.org/jcstress pull/125/head:pull/125` \
`$ git checkout pull/125`
`$ git checkout pull/125` \
`$ git pull https://git.openjdk.org/jcstress pull/125/head`
</details>
Checkout …
=> 7903407: jcstress: Main cannot compile with -Werror due to URL deprecation

jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Control.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/WorkerSync.java
There is a reasonable expectation that once `@State` object is created, it would eventually be acted upon. In fact, the Javadoc for `@Actor`/`@Arbiter` mentions that actor methods would be called on each state object exactly once. There are cases where users rely on this implicit lifecycle assumption to perform cleanups at `@Arbiter` methods.
Unfortunately, once jcstress leaves the test, it keeps last created state object slice unprocessed, which breaks this assumption.
---------
* [CODETOOLS-7903383](https://bugs.openjdk.org/browse/CODETOOLS-7903383): jcstress: All State objects should be processed
`$ git fetch https://git.openjdk.org/jcstress pull/124/head:pull/124` \
`$ git checkout pull/124`
Update a local …
=> 7903383: jcstress: All State objects should be processed

jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Different JDKs have differing opinions on the availability of UseBiasedLocking. For better locking path coverage, we might want to sense and add these options if available.
---------
* [CODETOOLS-7903408](https://bugs.openjdk.org/browse/CODETOOLS-7903408): jcstress: Add BiasedLocking options in test configurations
`$ git fetch https://git.openjdk.org/jcstress pull/126/head:pull/126` \
`$ git checkout pull/126`
`$ git checkout pull/126` \
`$ git pull https://git.openjdk.org/jcstress pull/126/head`
</details>
`$ git pr checkout 126`
`$ git pr show -t 126`
</details> …
=> 7903408: jcstress: Add BiasedLocking options in test configurations

jcstress-test-gen/src/main/resources/copy/arrays/X-LargeArraycopy.java.template, jcstress-test-gen/src/main/resources/copy/arrays/X-LargeArraysCopyOf.java.template, jcstress-test-gen/src/main/resources/copy/arrays/X-LargeClone.java.template, jcstress-test-gen/src/main/resources/copy/arrays/X-LargeManual.java.template, jcstress-test-gen/src/main/resources/defaultValues/X-ArrayLargeDefaultValuesTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayLargeInitClassTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayLargeInitLengthTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayLargeInitTest.java.template, jcstress-test-gen/src/main/resources/tearing/X-ArrayLargeTearingTest.java.template
These frequently time out on slower development boards.
---------
* [CODETOOLS-7903420](https://bugs.openjdk.org/browse/CODETOOLS-7903420): jcstress: Trim down the large array tests
`$ git fetch https://git.openjdk.org/jcstress pull/130/head:pull/130` \
`$ git checkout pull/130`
`$ git checkout pull/130` \
`$ git pull https://git.openjdk.org/jcstress pull/130/head`
</details>
`$ git pr checkout 130`
`$ git pr show -t 130`
</details>
<a …
=> 7903420: jcstress: Trim down the large array tests

jcstress-core/src/main/java/org/openjdk/jcstress/ForkedMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/AbstractThread.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java
Currently, we hold on to lots of state/results object from the test root, and from the fields in the checker/actor threads. This apparently is the source of some OOMEs/timeouts on smaller devices. We can make the lifecycle more explicit.
---------
* [CODETOOLS-7903423](https://bugs.openjdk.org/browse/CODETOOLS-7903423): jcstress: Improve footprint by managing object lifecycles better
`$ git fetch https://git.openjdk.org/jcstress pull/132/head:pull/132` \
`$ git checkout pull/132`
`$ git checkout pull/132` \
`$ git pull https://git.openjdk.org/jcstress pull/132/head`
</details>
`$ git pr checkout 132` …
=> 7903423: jcstress: Improve footprint by managing object lifecycles better

jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ResourceEstimator.java
On slow boards, sometimes the tests are stalling due to long GCs/compilations, etc. Resource sanity checks do not catch this, because they move very fast to larger lengths. It would be better to improve this.
---------
* [CODETOOLS-7903424](https://bugs.openjdk.org/browse/CODETOOLS-7903424): jcstress: Improve reliability of resource sanity checks
`$ git fetch https://git.openjdk.org/jcstress pull/133/head:pull/133` \
`$ git checkout pull/133`
`$ git checkout pull/133` \
`$ git pull https://git.openjdk.org/jcstress pull/133/head`
</details>
`$ git pr checkout 133`
`$ …
=> 7903424: jcstress: Improve reliability of resource sanity checks

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Small boards apparently timeout some allocation-hungry tests, because on-demand commit during the page allocation stalls a lot. We can make it better by automatically enabling `-XX:+AlwaysPreTouch`.
---------
* [CODETOOLS-7903425](https://bugs.openjdk.org/browse/CODETOOLS-7903425): jcstress: Pre-touch Java heap to avoid allocation stalls
`$ git fetch https://git.openjdk.org/jcstress pull/134/head:pull/134` \
`$ git checkout pull/134`
`$ git checkout pull/134` \
`$ git pull https://git.openjdk.org/jcstress pull/134/head`
</details>
`$ git pr checkout 134`
`$ git pr show …
=> 7903425: jcstress: Pre-touch Java heap to avoid allocation stalls

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java
There is an evidence that some tests fragment the heap significantly, without any recourse -- for example with humongous allocations in the large array tests. The current estimate of "take half of the heap for the test" is cutting it dangerously close. G1 routinely fails some of the init.arrays.large tests because of this.
---------
* [CODETOOLS-7903428](https://bugs.openjdk.org/browse/CODETOOLS-7903428): jcstress: Adjust max memory per test
`$ git fetch https://git.openjdk.org/jcstress pull/136/head:pull/136` \
`$ git checkout pull/136`
`$ git checkout pull/136` \
`$ git pull https://git.openjdk.org/jcstress pull/136/head`
</details>
<details><summary>Using Skara CLI …
=> 7903428: jcstress: Adjust max memory per test

jcstress-test-gen/src/main/java/org/openjdk/jcstress/chapters/Chapter0aTestGenerator.java, jcstress-test-gen/src/main/java/org/openjdk/jcstress/chapters/Chapter0eTestGenerator.java, jcstress-test-gen/src/main/resources/accessAtomic/X-ArrayAtomicityTest.java.template, jcstress-test-gen/src/main/resources/accessAtomic/X-FieldAtomicityTest.java.template, jcstress-test-gen/src/main/resources/accessAtomic/X-FieldConflictAtomicityTest.java.template, jcstress-test-gen/src/main/resources/acqrel/X-FieldAcqRelTest.java.template, jcstress-test-gen/src/main/resources/coherence/X-ArrayCoherenceTest.java.template, jcstress-test-gen/src/main/resources/coherence/X-FieldCoherenceTest.java.template, jcstress-test-gen/src/main/resources/defaultValues/X-ArrayDefaultValuesTest.java.template, jcstress-test-gen/src/main/resources/defaultValues/X-ArrayLargeDefaultValuesTest.java.template, jcstress-test-gen/src/main/resources/defaultValues/X-FieldDefaultValuesTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayInitClassTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayInitLengthTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayInitTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayLargeInitClassTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayLargeInitLengthTest.java.template, jcstress-test-gen/src/main/resources/init/X-ArrayLargeInitTest.java.template, jcstress-test-gen/src/main/resources/init/X-FieldInitClassTest.java.template, jcstress-test-gen/src/main/resources/init/X-FieldInitTest.java.template, jcstress-test-gen/src/main/resources/tearing/X-ArrayLargeTearingTest.java.template, jcstress-test-gen/src/main/resources/tearing/X-ArrayTearingTest.java.template, jcstress-test-gen/src/main/resources/tearing/X-FieldTearingTest.java.template
With Loom and Lilliput work, we want to test synchronized locks more broadly. Extending existing tests to also test synchronized would be beneficial.
---------
* [CODETOOLS-7903429](https://bugs.openjdk.org/browse/CODETOOLS-7903429): jcstress: Increase synchronized locks coverage
`$ git fetch https://git.openjdk.org/jcstress pull/137/head:pull/137` \
`$ git checkout pull/137`
`$ git checkout pull/137` \
`$ git pull https://git.openjdk.org/jcstress pull/137/head`
</details>
`$ git pr checkout 137`
`$ git pr show -t 137`
</details>
<details><summary>Using diff …
=> 7903429: jcstress: Increase synchronized locks coverage

.github/workflows/pre-integration.yml, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/AbstractThread.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/topology/AbstractTopology.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/topology/LinuxProcfsTopology.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/topology/LinuxSysfsTopology.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/topology/PresetRegularTopology.java
We need to start testing 21-ea for upcoming release.
---------
* [CODETOOLS-7903489](https://bugs.openjdk.org/browse/CODETOOLS-7903489): JCStress: Upgrade pre-integration workflows
`$ git fetch https://git.openjdk.org/jcstress.git pull/138/head:pull/138` \
`$ git checkout pull/138`
`$ git checkout pull/138` \
`$ git pull https://git.openjdk.org/jcstress.git pull/138/head`
</details>
`$ git pr checkout 138`
`$ git pr show -t 138`
</details>
<a …
=> 7903489: JCStress: Upgrade pre-integration workflows

.github/workflows/pre-integration.yml, jcstress-benchmarks/src/main/java/org/openjdk/jcstress/SampleTestBench.java, jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/TimeBudget.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ConsoleReportPrinter.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/grading/ReportUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/processors/JCStressTestProcessor.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/ForkedTestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/Runner.java, jcstress-core/src/main/java/org/openjdk/jcstress/infra/runners/TestConfig.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/TimeValue.java
Real-world testing with jcstress frequently runs into capacity problems. There are usually tons of tests in the suite, and there are many JVM options that default runner is traversing by default. This often comes as a nasty surprise for the testers, when the full run starts taking months.
There are "run profiles", selected with `-m`, which are supposed to help here, but they are not that handy to use, and are following the hand-selected hard-coded settings in the harness options.
Instead, we can do a better thing: introduce the "run time budget" option, where a user can say "I have around X hours to run these tests, figure out the best test configuration to fit this time".
This would make jcstress naturally usable in nightly runs, where we can ask for 1 hour run, weekly runs, where we can …
=> 7903491: jcstress: Run time budget

jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/seqcst/SeqCstTraceGenerator.java
Found this while peeking into the generated code: the arbiters code is not `synchronized` for sync tests, although it should match what other threads are doing. This seems to be innocuous on current platforms, because arbiter always runs "last" with the relevant volatile sychronization. This is not guaranteed to work generally, though.
---------
* [CODETOOLS-7903494](https://bugs.openjdk.org/browse/CODETOOLS-7903494): jcstress: seqcst tests arbiters should take the lock (**Bug** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/140/head:pull/140` \
`$ git checkout pull/140`
`$ git checkout pull/140` \
`$ git pull https://git.openjdk.org/jcstress.git pull/140/head` …
=> 7903494: jcstress: seqcst tests arbiters should take the lock

jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/TestGenerator.java, jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/seqcst/SeqCstTraceGenerator.java
Many @Actor-s in generated tests do not actually require a result. Avoiding the unnecessary result load optimizes the interpreter and C1.
---------
* [CODETOOLS-7903495](https://bugs.openjdk.org/browse/CODETOOLS-7903495): jcstress: Generated test actors should not request the result when not needed (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/141/head:pull/141` \
`$ git checkout pull/141`
`$ git checkout pull/141` \
`$ git pull https://git.openjdk.org/jcstress.git pull/141/head`
</details>
`$ git pr checkout 141`
`$ git pr show -t 141` …
=> 7903495: jcstress: Generated test actors should not request the result when not needed

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java, jcstress-core/src/main/java/org/openjdk/jcstress/TimeBudget.java, jcstress-test-gen/src/main/java/org/openjdk/jcstress/generator/seqcst/SeqCstTraceGenerator.java
Current full jcstress run takes about 60+ days on 36-core machine. This is driven by too many test configurations tested in the default config. We can cut down the test times (again) by re-examining the default run options.
---------
* [CODETOOLS-7903493](https://bugs.openjdk.org/browse/CODETOOLS-7903493): jcstress: Cut down test configurations (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/142/head:pull/142` \
`$ git checkout pull/142`
`$ git checkout pull/142` \
`$ git pull https://git.openjdk.org/jcstress.git pull/142/head`
</details>
`$ git pr checkout 142`
View PR …
=> 7903493: jcstress: Cut down test configurations

.github/workflows/pre-integration.yml
Node 16 is getting deprecated in GHA, we need to bump the versions for some GHA actions.
---------
* [CODETOOLS-7903679](https://bugs.openjdk.org/browse/CODETOOLS-7903679): jcstress: Upgrade some actions to avoid deprecated Node 16 (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/146/head:pull/146` \
`$ git checkout pull/146`
`$ git checkout pull/146` \
`$ git pull https://git.openjdk.org/jcstress.git pull/146/head`
</details>
`$ git pr checkout 146`
`$ git pr show -t 146`
</details>
Download this …
=> 7903679: jcstress: Upgrade some actions to avoid deprecated Node 16

jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
We do not need many debug JVM helpers for low-level concurrency testing. Opting out of them allows significantly faster performance for fastdebug builds.
---------
* [CODETOOLS-7903703](https://bugs.openjdk.org/browse/CODETOOLS-7903703): jcstress: Better performance for debug JVMs by disabling unnecessary debugging helpers (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/148/head:pull/148` \
`$ git checkout pull/148`
`$ git checkout pull/148` \
`$ git pull https://git.openjdk.org/jcstress.git pull/148/head`
</details>
`$ git pr checkout 148`
View PR using the GUI difftool: …
=> 7903703: jcstress: Better performance for debug JVMs by disabling unnecessary debugging helpers

.github/workflows/pre-integration.yml
We always playing the catchup game with runners. Let's just default to latest runners for every OS flavor.
---------
* [CODETOOLS-7903891](https://bugs.openjdk.org/browse/CODETOOLS-7903891): jcstress: Switch to latest runner versions (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/154/head:pull/154` \
`$ git checkout pull/154`
`$ git checkout pull/154` \
`$ git pull https://git.openjdk.org/jcstress.git pull/154/head`
</details>
`$ git pr checkout 154`
`$ git pr show -t 154`
</details>
Download …
=> 7903891: jcstress: Switch to latest runner versions

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/CompileMode.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
WIP.
[JDK-8351997](https://bugs.openjdk.org/browse/JDK-8351997) shows there is a gap in current configuration coverage with jcstress. When split compilation is enabled, harness asks to int/C1/C2 each actor method separately. Unfortunately, there are cases in Hotspot where the barrier scheme depends on whether C2 is globally enabled. [JDK-8351997](https://bugs.openjdk.org/browse/JDK-8351997) would fail split int/C1 test with C2 globally disabled.
Therefore, harness should run with global int/C1/C2 modes even with split compilation. This complicates testing matrix quite a bit, but it should capture bugs like [JDK-8351997](https://bugs.openjdk.org/browse/JDK-8351997) more reliably.
---------
* [CODETOOLS-7904034](https://bugs.openjdk.org/browse/CODETOOLS-7904034): jcstress: Run with global …
=> 7904034: jcstress: Run with global int/C1/C2 modes even with split compilation

jcstress-core/src/main/java/org/openjdk/jcstress/Options.java
With incoming test changes, we have more configurations to run. To keep run time within reasonable bounds, it makes more sense to drop default -fsm to 1. Users could still re-define it to larger values to get more stress out of individual tests.
---------
* [CODETOOLS-7904040](https://bugs.openjdk.org/browse/CODETOOLS-7904040): jcstress: Drop default stress-fork to 1 (**Bug** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/170/head:pull/170` \
`$ git checkout pull/170`
`$ git checkout pull/170` \
`$ git pull https://git.openjdk.org/jcstress.git pull/170/head`
</details>
`$ git pr checkout …
=> 7904040: jcstress: Drop default stress-fork to 1

jcstress-core/src/main/java/org/openjdk/jcstress/JCStress.java, jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupport.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/AffinitySupportPrepareMain.java, jcstress-core/src/main/java/org/openjdk/jcstress/os/OSSupport.java, jcstress-core/src/main/java/org/openjdk/jcstress/util/StringUtils.java, jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
Current jcstress uses JNA for affinity setup. It causes lots of warnings when running with JDK 25.
This PR tries to fix most of them.
---------
* [CODETOOLS-7904042](https://bugs.openjdk.org/browse/CODETOOLS-7904042): jcstress: Native access warnings when running with JDK 25 (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/171/head:pull/171` \
`$ git checkout pull/171`
`$ git checkout pull/171` \
`$ git pull https://git.openjdk.org/jcstress.git pull/171/head`
</details>
`$ git pr checkout 171`
`$ git pr show -t 171`
</details> …
=> 7904042: jcstress: Native access warnings when running with JDK 25

jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/advanced/AdvancedJMM_15_VolatilesAreNotFences.java
In [CODETOOLS-7904033](https://bugs.openjdk.org/browse/CODETOOLS-7904033), I made a little mistake of rewriting Unsafe.storeFence to VarHandle.acquireFence. It should be VarHandle.releaseFence. That subtest is currently failing on AArch64.
---------
* [CODETOOLS-7904043](https://bugs.openjdk.org/browse/CODETOOLS-7904043): jcstress: AdvancedJMM_15_VolatilesAreNotFences.Fences is failing after CODETOOLS-7904033 (**Bug** - P4)
`$ git fetch https://git.openjdk.org/jcstress.git pull/173/head:pull/173` \
`$ git checkout pull/173`
`$ git checkout pull/173` \
`$ git pull https://git.openjdk.org/jcstress.git pull/173/head`
</details> …
=> 7904043: jcstress: AdvancedJMM_15_VolatilesAreNotFences.Fences is failing after CODETOOLS-7904033
